# Generated by Django 4.2.11 on 2024-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='book_pictures'),
        ),
    ]
