# Generated by Django 4.2.11 on 2024-05-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.URLField(blank=True, null=True),
        ),
    ]
