# Generated by Django 4.2.11 on 2024-05-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='downloading_url',
        ),
    ]
