# Generated by Django 4.2.11 on 2024-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_book_book_downloading_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
